const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME';
const RESET_FILTER = 'RESET_FILTER';
const FILTER_TYPE_DIET = 'FILTER_TYPE_DIET';
const ORDERBY = 'ORDERBY';
const ADD_RECIPE = 'ADD_RECI';
const GET_RECIPES_BY_DETAIL = 'GET_RECIPES_BY_DETAIL';
const GET_RECIPES = 'GET_RECIPES';
const FILTER_ORGIN = 'FILTER_ORGIN';
const GET_DIETS = 'GET_DIETS';
const SET_RECIPE_CLEAN = 'SET_RECIPE_CLEAN';

export {
	ADD_RECIPE,
	FILTER_TYPE_DIET,
	FILTER_ORGIN,
	RESET_FILTER,
	ORDERBY,
	GET_RECIPES,
	GET_RECIPES_BY_DETAIL,
	SET_RECIPE_CLEAN,
	GET_RECIPES_BY_NAME,
	GET_DIETS,
};
